### ISSUE TITLE
Great tutorial... one issue with stylesheet

### ISSUE THREAD

**Issue by rice-big0923** [mahbub08kuet/hbs-mongo-with-express4#1]
Hello, I wanted to say thank you for this terrific tutorial. I needed to learn how to access and edit existing data in MongoDB directly, but every other book or tutorial I found used Mongoose and became way too complicated. Yours was simple, direct, and it actually worked!  Only one tiny issue: your stylesheet is in a folder called 'stylesheets' but your layout.hbs file is looking for a folder called 'css.' Thanks again.

**Comment by iamcrypticcoder** [comment]
Thanks for your appreciation. Would you please check pull request 2 change ? Let me know is it correct ?
https://github.com/mahbub08kuet/hbs-mongo-with-express4/pull/2
